In [ ]:
import pandas as pd
import io
import re

In [ ]:
nama_file_asli = 'the2025.csv'
nama_file_baru = 'the2025_cleaned.csv'

df = pd.read_csv(nama_file_asli)

kolom_yang_disimpan = ['Rank', 'Name Country/Region']
df_cleaned = df[kolom_yang_disimpan]

df_cleaned.to_csv(nama_file_baru, index=False)

print(df_cleaned.head())

Data Asli (5 baris pertama):
  Rank                                Name Country/Region Overall  Teaching  \
0    1                 University of OxfordUnited Kingdom    98.5      96.8
1    2  Massachusetts Institute of TechnologyUnited St...    98.1      99.2
2    3                    Harvard UniversityUnited States    97.7      97.3
3    4                  Princeton UniversityUnited States    97.5      98.3
4    5              University of CambridgeUnited Kingdom    97.4      95.9

   Research Environment  Research Quality  Industry  International Outlook
0                 100.0              98.8      99.6                   97.3
1                  96.0              99.7     100.0                   93.8
2                  99.9              99.3      85.7                   90.1
3                  98.0              98.9      96.9                   87.4
4                  99.9              97.6      88.4                   97.1

==============================

Data setelah dibersihkan (hanya kolom Rank, Name Country/Region):
  Rank                                Name Country/Region
0    1                 University of OxfordUnited Kingdom
1    2  Massachusetts Institute of TechnologyUnited St...
2    3                    Harvard UniversityUnited States
3    4                  Princeton UniversityUnited States
4    5              University of CambridgeUnited Kingdom

==============================

File 'the2025_cleaned.csv' telah berhasil dibuat dan siap diunduh dari panel file.

In [ ]:
nama_file_asli = 'cwur2025.csv'
nama_file_hasil_csv = 'cwur2025_cleaned.csv'

df = pd.read_csv(nama_file_asli)

df_cleaned = df[['World Rank', 'Institution']].copy()

def clean_rank(rank_text):
    match = re.match(r'^\d+', str(rank_text))
    return match.group(0) if match else None

df_cleaned['World Rank'] = df_cleaned['World Rank'].apply(clean_rank)
df_cleaned.dropna(inplace=True)
df_cleaned['World Rank'] = df_cleaned['World Rank'].astype(int)

df_cleaned.to_csv(nama_file_hasil_csv, index=False)

print(df_cleaned.head())

File 'cwur2025_cleaned.csv' telah berhasil dibuat!

Data yang disimpan (5 baris pertama):
   World Rank                            Institution
0           1                     Harvard University
1           2  Massachusetts Institute of Technology
2           3                    Stanford University
3           4                University of Cambridge
4           5                   University of Oxford

In [ ]:
nama_file_asli = '2026QS.xlsx'
nama_file_baru = 'QS_2026_cleaned.csv'

df = pd.read_excel(nama_file_asli, skiprows=1)
df.columns = df.iloc[0]
df = df.drop(df.index[0]).reset_index(drop=True)

df_cleaned = df[['Rank', 'Name']]
df_cleaned = df_cleaned.rename(columns={'Rank': 'Rank', 'Name': 'Institution'})

df_cleaned.to_csv(nama_file_baru, index=False)

print(df_cleaned.head())

File 'QS_2026_cleaned.csv' telah berhasil dibuat!

5 baris pertama dari data yang sudah dibersihkan:
0 Rank                                  Institution
0    1  Massachusetts Institute of Technology (MIT)
1    2                      Imperial College London
2    3                          Stanford University
3    4                         University of Oxford
4    5                           Harvard University